defaults:
  - /dataset: waterbirds_clip_full.yaml
  - _self_

seed: 42
callbacks:
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${hydra:run.dir}
  name: classifier

trainer:
  _target_: trainer.ClassifierTrainer
  num_classes_per_label:  [2,2]
  model:
    _target_: models.ClipClassifer
    num_classes_per_label:  ${classifier.trainer.num_classes_per_label}
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 3.0e-4
    weight_decay: 1.0e-3
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 3000

training_config:
  max_steps: ${classifier.trainer.scheduler.T_max}
  accelerator: gpu
  gradient_clip_val: 1.0
  enable_checkpointing: true
  precision: 16-mixed