train_dataset:
  _target_: datasets.coloredMNIST.ColoredMNIST
  root_dir: data
  download: True
  train: True
  support: 'uniform'
  
val_dataset:
  _target_: datasets.coloredMNIST.ColoredMNIST
  root_dir: data
  download: True
  train: False
  support: 'uniform'
  
train_dataloader:
  batch_size: 256
  num_workers: 4
  persistent_workers: True
  shuffle: True

val_dataloader:
  batch_size: 256
  num_workers: 4
  persistent_workers: True
  shuffle: False

