defaults:
  - /dataset: shapes3d_orthogonal
  - _self_

model:
  _target_: models.clip_unet.ProjUnetConditional
  input_dim: 768
  num_class_per_label: [2,2]
  interaction: sum
  sample_size: 32
  in_channels: 1
  out_channels: 1 
  layers_per_block: 2
  block_out_channels: [ 56, 112, 168]  #[56, 112, 168] 112,224,448need to check on this hyperparameter and increasing the number of channels
  attention_head_dim:  8   #what is the standard value for this hyperparameter
  class_embed_type: null
  norm_num_groups: 8
  act_fn: silu
  down_block_types:
    - DownBlock2D
    - AttnDownBlock2D
    - AttnDownBlock2D
  up_block_types: 
    - AttnUpBlock2D
    - AttnUpBlock2D
    - UpBlock2D
    
noise_scheduler:
  _target_: diffusers.DDPMScheduler
  num_train_timesteps: 1000
  clip_sample: true
  prediction_type: epsilon
  beta_schedule: linear

seed: 42
checkpoint_path: checkpoints/shapes3d/shapes3d_partial_coind.ckpt

classifier: 
  _target_: cs_classifier.models.MultiLabelClassifier
  base_model: 
    _target_: torchvision.models.resnet18
  num_classes_per_label: ${model.num_class_per_label}
  
classifer_checkpoint: checkpoints/cs_classifier/shapes3d.ckpt  





