defaults:
  - /diffusion: waterbirds_dm
  - /dataset: waterbirds_clip_orthogonal
  - _self_

seed: 42
callbacks:
  ema_callback:
    _target_ : score.ema.EMA
    decay: 0.9999
    validate_original_weights: true
    every_n_steps: 100
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  generation_metrics:
    _target_: callbacks.tracker.GenerationMetrics
    sampling_pipe: 
      _target_: score.pipelines.CondDDIMPipeline
      _partial_: true
    metrics: ["cs"] 
    log_interval: 50
    num_classes_per_label: ${diffusion.model.num_class_per_label}
    output_dir: ${hydra:run.dir}  
    classifier: 
      _target_:  cs_classifier.models.ClipClassifer
      num_classes_per_label: ${diffusion.model.num_class_per_label}
    classifer_checkpoint: checkpoints/cs_classifier/waterbirds.ckpt       
    
loggers:
  tensorboard_logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ${hydra:run.dir}
    name: tensorboard
  csv_logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:run.dir}
    name: csv

trainer:
  max_steps: ${diffusion.scheduler.num_training_steps}
  accelerator: gpu
  gradient_clip_val: 1.0
  enable_checkpointing: true




